// <auto-generated />
namespace LanguageSchoolApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Coursedescriptionhastypentext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Coursedescriptionhastypentext));
        
        string IMigrationMetadata.Id
        {
            get { return "201709281725102_Course description has type ntext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
