// <auto-generated />
namespace LanguageSchoolApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CourseResultCoursePointshaverange0100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseResultCoursePointshaverange0100));
        
        string IMigrationMetadata.Id
        {
            get { return "201709282037367_CourseResult CoursePoints have range 0-100"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
